-- ============================================================
-- DEED · Obsahová doména (feed) — schéma v1   [DRAFT — NEAPLIKOVANÉ]
-- ------------------------------------------------------------
-- Rozširuje identitu (0001) o OBSAH: príspevky, udalosti, podpory,
-- sledovanie, notifikácie, adresár charít. Autor = ucet(id).
--
-- Jadrová tabuľka `prispevok` pokrýva skutok/žiadosť/zbierku/talent/
-- workshop/case naprieč modulmi: engine polia (geo/skóre/typ/modul…) sú
-- STĹPCE (indexovateľné), modulové detaily idú do `data jsonb`. Sedí s
-- lib/feed.ts — filter podľa okruhu/prahu/zoradenia ostáva client-side.
--
-- POZN. RLS: SELECT je verejné (feed/adresár sú verejné). Zápis je
--       TEST-ONLY (povolí všetko) do napojenia Supabase Auth (Fáza 5),
--       rovnako ako v 0001 (advisor 0024 je očakávaný).
-- Identifikátory bez diakritiky (ASCII); hodnoty s diakritikou OK.
-- ============================================================

-- ---------- PRÍSPEVOK (jadro feedu) ----------
create table public.prispevok (
  id            uuid primary key default gen_random_uuid(),
  cislo         bigint generated by default as identity, -- zobrazené "č. 120051" (seed zachová pôvodné num)
  autor_ucet_id uuid references public.ucet(id) on delete set null,  -- NULL = seed/systém
  autor_nazov   text,            -- denormalizovaný autor (seed bez účtu / display)
  autor_ini     text,            -- iniciála do avataru
  autor_pfp     text,            -- farba/akcent avataru
  autor_karma   text,            -- Novacik/Bronze/Silver/Gold/Legend (display)
  modul         text not null check (modul in ('good','help','charity','workshop')),
  typ           text not null check (typ in ('skutok','ziadost','charita','ponuka','talent','workshop','case')),
  kat           text,            -- kategória (Komunita/Priroda/…) alebo doména (sport/eko/…)
  titul         text,
  popis         text,
  emoji         text,
  media         jsonb not null default '{}'::jsonb,     -- {druh, fotky[], video, poster}
  -- geo (akcie v okolí / okruh feedu) — verejne sa ukáže len `lok`
  lat           double precision,
  lng           double precision,
  mesto         text,
  stvrt         text,
  lok           text,            -- zobrazený text lokality ("Trenčín · Sihoť")
  narodne       boolean not null default false,         -- národná kampaň (mimo geo okruhu)
  typ_situacie  text not null default 'normal' check (typ_situacie in ('normal','kriza')),
  skore         numeric(4,1) not null default 0,        -- ~0–11 (placeholder, neskôr AI+GPS)
  overene       boolean not null default false,
  topovane      boolean not null default false,
  vyznam        text,            -- "Výnimočný skutok" / importance
  -- fundraising (žiadosť/zbierka)
  ciel          numeric(12,2),
  vyzbierane    numeric(12,2),
  pomocnici     int,             -- počet zapojených
  -- počty
  lajky         int not null default 0,
  podpora_count int not null default 0,
  -- modulové extra (workshop: seats/cena/priceTxt/rating/profi/b2b;
  --   charity: charLevel/comp/badgeL/tag; help: odbornik/sponzor/ikona;
  --   aktivity: size/drr/source/mine)
  data          jsonb not null default '{}'::jsonb,
  vytvorene     timestamptz not null default now(),
  aktualizovane timestamptz not null default now()
);
comment on table public.prispevok is 'Jadro feedu — skutok/žiadosť/zbierka/talent/workshop/case naprieč modulmi.';

-- ---------- UDALOSŤ (nástenka / akcie v okolí) ----------
create table public.udalost (
  id        uuid primary key default gen_random_uuid(),
  modul     text not null default 'good',
  kedy_text text,                -- zobrazené ("ŠTV 18:00") — reálny timestamptz pribudne neskôr
  kedy      timestamptz,
  titul     text not null,
  kto       text,                -- organizátor
  zdroj     text check (zdroj in ('Komunita','Mesto','Partner')),
  kat       text,
  popis     text,
  miesto    text,
  kapacita  text,
  lat       double precision,
  lng       double precision,
  top       boolean not null default false,
  vytvorene timestamptz not null default now()
);

-- ---------- PODPORA („Čo podporujem" + dar na príspevok) ----------
-- Doplnok k `dar` (0001 = pasívne dary hostí); tu IN-APP podpora viazaná na príspevok.
create table public.podpora (
  id           bigint generated always as identity primary key,
  ucet_id      uuid references public.ucet(id) on delete set null,    -- podporovateľ (NULL = anon)
  prispevok_id uuid references public.prispevok(id) on delete cascade,
  prijemca     text,            -- denormalizovaný príjemca (ak cieľ nie je príspevok)
  suma         numeric(12,2) not null,
  kanal        text not null check (kanal in ('deed','fiat','sms')),  -- jednotka sumy
  zobrazenie   text,            -- anonym/…
  vyzbierane   numeric(12,2),   -- snapshot progresu v čase podpory
  ciel         numeric(12,2),
  cas          timestamptz not null default now()
);

-- ---------- SLEDOVANIE (koho sledujem — afinitná váha feedu) ----------
create table public.sledovanie (
  id            bigint generated always as identity primary key,
  ucet_id       uuid not null references public.ucet(id) on delete cascade,  -- sledujúci
  autor         text not null,   -- sledovaný (display meno; seed bez účtu)
  autor_ucet_id uuid references public.ucet(id) on delete set null,
  typ           text not null default 'osoba' check (typ in ('osoba','org')),
  cas           timestamptz not null default now(),
  unique (ucet_id, autor)
);

-- ---------- NOTIFIKÁCIA (per-user, realtime) ----------
create table public.notifikacia (
  id      bigint generated always as identity primary key,
  ucet_id uuid references public.ucet(id) on delete cascade,   -- príjemca (NULL = broadcast/seed)
  kat     text not null check (kat in ('skutky','penazenka','sledovane','socialne','deed')),
  ikona   text,
  col     text,            -- theme-aware akcent (var(--a-*))
  titul   text not null,
  text    text,
  nove    boolean not null default true,
  agg     boolean not null default false,   -- agregovaný súhrn (mikro-podpory)
  cas     timestamptz not null default now()
);

-- ---------- ADRESÁR CHARÍT & OZ ----------
create table public.adresar_charita (
  id          bigint generated always as identity primary key,
  sekcia      text,
  skratka     text,
  nazov       text not null,
  popis       text,
  level       text check (level in ('Legend','Gold','Silver','Bronze')),
  ponuky      text,            -- "💶 🙋 📦"
  org_ucet_id uuid references public.ucet(id) on delete set null,  -- link na registrovanú org
  aktivny     boolean not null default true,
  poradie     int not null default 0
);

-- ---------- INDEXY (feed: geo bbox + skóre + čerstvosť + výber) ----------
create index on public.prispevok (modul);
create index on public.prispevok (typ);
create index on public.prispevok (narodne);
create index on public.prispevok (skore desc);
create index on public.prispevok (vytvorene desc);
create index on public.prispevok (lat, lng);       -- bounding-box prefilter pre okruh
create index on public.podpora (ucet_id);
create index on public.podpora (prispevok_id);
create index on public.sledovanie (ucet_id);
create index on public.notifikacia (ucet_id, cas desc);
create index on public.udalost (modul);

-- ---------- RLS (TEST-ONLY: povoliť všetko pre anon/authenticated) ----------
-- SELECT je verejné zámerne (feed/adresár sú verejné). Zápis sa zamkne reálnymi
-- politikami po napojení Supabase Auth (Fáza 5) — vtedy `test_all_access` nahradíme
-- per-tabuľkovými politikami (autor smie meniť len svoje, podpora viazaná na auth.uid() …).
do $$
declare t text;
begin
  foreach t in array array[
    'prispevok','udalost','podpora','sledovanie','notifikacia','adresar_charita'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists test_all_access on public.%I', t);
    execute format(
      'create policy test_all_access on public.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;
