-- DEED · SEED Help — vygenerované z features/help/mock.ts
-- Diskriminátor data.help=true (good.feed + top-hrdinovia ich vylúčia, aby Help
-- nepresiakol do Domova/Top). Pôvodný typ v data.typ ('charity' round-trip);
-- stĺpec typ je CHECK-safe ('charity'→'charita'). suma→vyzbierane, ludia→pomocnici.
-- Idempotentné: zmaž len Help riadky (data ? 'help'), potom vlož. (NIKDY truncate.)

delete from public.prispevok where data ? 'help';

insert into public.prispevok (cislo, autor_nazov, autor_karma, modul, typ, kat, popis, emoji, media, lat, lng, lok, narodne, typ_situacie, skore, overene, ciel, vyzbierane, pomocnici, lajky, podpora_count, data, vytvorene) values
(7, 'Marek B.', 'Gold', 'help', 'ziadost', 'Zdravie', 'Po operácii chrbtice potrebujem rehabilitácie, ktoré poisťovňa neprepláca. Chcem sa vrátiť do práce a k deťom.', '🦴', '{"druh":null,"fotky":["/img/chrbtica.jpg","https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.875, 18.03, 'Trenčín · Juh', false, 'normal', 8, true, 1800, 1250, 52, 0, 52, '{"help":true,"id":7,"typ":"ziadost","velkost":"velka","sponzor":{"meno":"LIDL","suma":500},"avatar":"https://i.pravatar.cc/100?img=68"}'::jsonb, now() - interval '0 days'),
(1, 'Rodina Kováčová', 'Silver', 'help', 'ziadost', 'Pomoc', 'V noci nám zhorel dom, ostali sme bez strechy s dvomi deťmi. Potrebujeme provizórne bývanie a základné veci.', '🔥', '{"druh":null,"fotky":["/img/dom.jpg","https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.892, 18.02, 'Trenčín · Zámostie', false, 'kriza', 9, true, 2200, 1430, 38, 0, 38, '{"help":true,"id":1,"typ":"ziadost","velkost":"velka","avatar":"https://i.pravatar.cc/100?img=47"}'::jsonb, now() - interval '0 days'),
(2, 'Mgr. Lucia D.', NULL, 'help', 'ponuka', 'Ucenie', 'Doučím matematiku a fyziku, 8 rokov praxe, certifikát doložený.', '🎓', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.894, 18.044, 'Centrum · online', true, 'normal', 4, false, NULL, NULL, NULL, 0, 5, '{"help":true,"id":2,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '0 days'),
(3, 'Charita XY', NULL, 'charity', 'charita', 'Priroda', 'Hľadá 10 dobrovoľníkov · výsadba stromov · sobota Brezina', 'XY', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.89, 18.05, NULL, false, 'normal', 6, false, NULL, NULL, NULL, 0, 20, '{"help":true,"id":3,"typ":"charity","sponzor":true}'::jsonb, now() - interval '0 days'),
(4, 'Jozef K.', NULL, 'help', 'ponuka', 'Komunita', 'Pomôžem so sťahovaním cez víkend.', '🧰', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.875, 18.03, 'Juh', false, 'normal', 2.5, false, NULL, NULL, NULL, 0, 3, '{"help":true,"id":4,"typ":"ponuka","velkost":"riadok","odbornik":false}'::jsonb, now() - interval '1 days'),
(5, 'Žofia K.', 'Bronze', 'help', 'ziadost', 'Zdravie', 'Po úraze tri mesiace bez príjmu, potrebujem na nájom a lieky.', '🩺', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.905, 18.03, 'Trenčín · Sihoť', false, 'normal', 5, true, 800, 520, 14, 0, 14, '{"help":true,"id":5,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=12"}'::jsonb, now() - interval '1 days'),
(6, 'Zelená plus', NULL, 'charity', 'charita', 'Komunita', 'Triedenie šatstva pre útulok · streda', 'ZP', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.882, 18.06, NULL, false, 'normal', 4, false, NULL, NULL, NULL, 0, 6, '{"help":true,"id":6,"typ":"charity","sponzor":false}'::jsonb, now() - interval '2 days'),
(8, 'Rodina Horváthová', 'Bronze', 'help', 'ziadost', 'Pomoc', 'Samoživiteľka s tromi deťmi — pokazila sa nám práčka a na novú nemám. Pranie pre päť ľudí ručne už nestíham.', '🧺', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.892, 18.02, 'Trenčín · Zámostie', false, 'normal', 6, true, 350, 120, 11, 0, 11, '{"help":true,"id":8,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=31"}'::jsonb, now() - interval '0 days'),
(9, 'Ing. Tomáš L.', NULL, 'help', 'ponuka', 'Komunita', 'Daňové a účtovné poradenstvo zadarmo pre seniorov a samoživiteľov. 15 rokov prax, pomôžem s priznaním aj odvolaním.', '🧾', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.894, 18.044, 'Centrum · online', true, 'normal', 4, false, NULL, NULL, NULL, 0, 6, '{"help":true,"id":9,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '0 days'),
(10, 'Štefan B. (71)', 'Silver', 'help', 'ziadost', 'Zdravie', 'Chodím na onkológiu do Bratislavy raz týždenne. Vlakom je to s mojím stavom veľmi ťažké, hľadám spolujazdu alebo odvoz.', '🚙', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.905, 18.03, 'Trenčín · Sihoť', false, 'normal', 5.5, true, NULL, NULL, NULL, 0, 14, '{"help":true,"id":10,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=52"}'::jsonb, now() - interval '0 days'),
(11, 'Peter H. — murár', NULL, 'help', 'ponuka', 'Komunita', 'Zadarmo opravím drobnosti seniorom — kvapkajúci kohútik, uvoľnená zásuvka, zaseknuté dvere. Stačí zavolať.', '🧰', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.875, 18.03, 'Juh', false, 'normal', 3.5, false, NULL, NULL, NULL, 0, 4, '{"help":true,"id":11,"typ":"ponuka","velkost":"riadok","odbornik":true}'::jsonb, now() - interval '1 days'),
(12, 'Mladá rodina K.', 'Bronze', 'help', 'ziadost', 'Zdravie', 'Dvojičky sa nám narodili predčasne. Potrebujeme špeciálne zdravotnícke pomôcky a monitor dychu, ktoré poisťovňa nehradí.', '👶', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.882, 18.06, 'Trenčín · Noviny', false, 'normal', 7, true, 2000, 760, 27, 0, 27, '{"help":true,"id":12,"typ":"ziadost","velkost":"velka","avatar":"https://i.pravatar.cc/100?img=45"}'::jsonb, now() - interval '0 days'),
(13, 'Lucia — kaderníčka', NULL, 'help', 'ponuka', 'Zdravie', 'Imobilným a seniorom ostrihám vlasy priamo doma, zadarmo. Maličkosť, ktorá vie veľmi potešiť.', '✂️', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.888, 18.052, 'Dlhé Hony', false, 'normal', 3, false, NULL, NULL, NULL, 0, 5, '{"help":true,"id":13,"typ":"ponuka","velkost":"riadok","odbornik":true}'::jsonb, now() - interval '1 days'),
(14, 'Mária V. — učiteľka', NULL, 'help', 'ponuka', 'Ucenie', 'Doučím slovenčinu a matematiku deťom, ktoré si platené doučovanie nemôžu dovoliť. Online aj naživo v knižnici.', '📕', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.894, 18.044, 'online', true, 'normal', 4, false, NULL, NULL, NULL, 0, 7, '{"help":true,"id":14,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '1 days'),
(15, 'Jozef P. (vozičkár)', 'Silver', 'help', 'ziadost', 'Pomoc', 'Do vchodu sa bez rampy nedostanem sám. Hľadám pomoc s vybudovaním bezbariérovej rampy a príspevok na materiál.', '♿', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.892, 18.02, 'Trenčín · Zámostie', false, 'normal', 5, true, 900, 540, 16, 0, 16, '{"help":true,"id":15,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=60"}'::jsonb, now() - interval '2 days'),
(16, 'Roman — automechanik', NULL, 'help', 'ponuka', 'Komunita', 'Pred zimou skontrolujem auto zadarmo samoživiteľkám — brzdy, svetlá, kvapaliny, gumy. Bezpečnosť detí je dôležitá.', '🔧', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.875, 18.03, 'Juh', false, 'normal', 3, false, NULL, NULL, NULL, 0, 4, '{"help":true,"id":16,"typ":"ponuka","velkost":"riadok","odbornik":true}'::jsonb, now() - interval '2 days'),
(17, 'Útulok Túlavá labka', 'Silver', 'help', 'ziadost', 'Komunita', 'Na zimu nám chýba krmivo a deky pre 40 psov a mačiek. Privítame aj materiálnu pomoc či venčiarov-dobrovoľníkov.', '🐾', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.87, 18.06, 'Trenčín · okraj', false, 'normal', 4.5, true, 600, 180, 22, 0, 22, '{"help":true,"id":17,"typ":"ziadost","velkost":"stredna"}'::jsonb, now() - interval '1 days'),
(18, 'Mgr. Eva R. — psychológ', NULL, 'help', 'ponuka', 'Zdravie', 'Bezplatné krízové konzultácie pre mladých v ťažkej situácii. Diskrétne, online, bez čakačky. Niekedy stačí, že vás niekto vypočuje.', '🧠', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.894, 18.044, 'online', true, 'normal', 5, false, NULL, NULL, NULL, 0, 9, '{"help":true,"id":18,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '0 days'),
(19, 'Charita Trenčín', 'Gold', 'help', 'ziadost', 'Pomoc', 'Naša nízkoprahová jedáleň vydáva denne 120 teplých obedov ľuďom bez domova. Pred zimou nám dochádzajú zásoby a teplé oblečenie.', '🍲', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=60","https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.894, 18.046, 'Trenčín · centrum', false, 'normal', 6, true, 2500, 940, 41, 0, 41, '{"help":true,"id":19,"typ":"ziadost","velkost":"velka","avatar":"https://i.pravatar.cc/100?img=13"}'::jsonb, now() - interval '0 days'),
(20, 'Stolárstvo Hôrka', NULL, 'help', 'ponuka', 'Komunita', 'Seniorom a samoživiteľom opravím nábytok zadarmo — vypadnuté dvierka, rozheganú stoličku, poličku. Materiál po dohode.', '🪚', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.875, 18.03, 'Trenčín · Juh', false, 'normal', 3, false, NULL, NULL, NULL, 0, 5, '{"help":true,"id":20,"typ":"ponuka","velkost":"riadok","odbornik":true}'::jsonb, now() - interval '1 days'),
(21, 'Útulok Túlavá labka', 'Silver', 'help', 'ziadost', 'Komunita', 'Cez zimu kŕmime 40 psov a mačiek. Chýba krmivo, deky a venčiari. Aj hodina týždenne s vodítkom pomôže.', '🐾', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.87, 18.062, 'Trenčín · okraj', false, 'normal', 5, true, 700, 220, 26, 0, 26, '{"help":true,"id":21,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=15"}'::jsonb, now() - interval '1 days'),
(22, 'Rodina Bieliková', 'Bronze', 'help', 'ziadost', 'Zdravie', 'Synovi (6) diagnostikovali autizmus. Potrebujeme na špeciálnu terapiu, ktorú poisťovňa nehradí. Každé euro nás posúva.', '🧩', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.905, 18.165, 'Trenčianske Teplice', false, 'normal', 4.5, true, 1500, 480, 13, 0, 13, '{"help":true,"id":22,"typ":"ziadost","velkost":"stredna","avatar":"https://i.pravatar.cc/100?img=26"}'::jsonb, now() - interval '1 days'),
(23, 'Klub mnohodetných rodín', 'Silver', 'help', 'ziadost', 'Pomoc', 'Pred školským rokom zbierame pomôcky, tašky a topánky pre 18 detí z piatich rodín v núdzi. Pomôže aj materiál.', '🎒', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.757, 17.832, 'Nové Mesto n. Váhom', false, 'normal', 6.5, true, 1400, 610, 29, 0, 29, '{"help":true,"id":23,"typ":"ziadost","velkost":"velka","avatar":"https://i.pravatar.cc/100?img=33"}'::jsonb, now() - interval '0 days'),
(24, 'Ing. Daniela K. — sociálna poradkyňa', NULL, 'help', 'ponuka', 'Komunita', 'Pomôžem zorientovať sa v dávkach, príspevkoch a žiadostiach pre ZŤP. Sprevádzanie na úrady. Zadarmo pre seniorov a rodiny v núdzi.', '📋', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.961, 18.19, 'Dubnica n. Váhom', false, 'normal', 6, false, NULL, NULL, NULL, 0, 7, '{"help":true,"id":24,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '1 days'),
(25, 'Detský domov Prievidza', 'Gold', 'help', 'ziadost', 'Zdravie', 'Pre 24 detí zháňame príspevok na letný tábor a plavecký výcvik. Pre mnohé z nich je to prvý výlet mimo domova.', '⛺', '{"druh":null,"fotky":["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60"],"video":null}'::jsonb, 48.774, 18.627, 'Prievidza', false, 'normal', 7, true, 3200, 1280, 34, 0, 34, '{"help":true,"id":25,"typ":"ziadost","velkost":"velka","avatar":"https://i.pravatar.cc/100?img=51"}'::jsonb, now() - interval '0 days'),
(26, 'IPčko — krízová linka', NULL, 'help', 'ponuka', 'Zdravie', 'Bezplatná internetová poradňa pre mladých v kríze. Anonymne, nonstop. Ak je ti ťažko, ozvi sa — sme tu pre teba.', '💬', '{"druh":null,"fotky":[],"video":null}'::jsonb, 48.894, 18.044, 'online · 24/7', true, 'normal', 6, false, NULL, NULL, NULL, 0, 18, '{"help":true,"id":26,"typ":"ponuka","velkost":"stredna","odbornik":true}'::jsonb, now() - interval '0 days');
