-- ============================================================
-- DEED · Payment Engine — jadro (ledger + 24h batch)   [Fáza 2]
-- ------------------------------------------------------------
-- `platba` = system-of-record pre KAŽDÝ pohyb peňazí (kanál, externý_id,
-- poplatok, marža, tip, stav, batch, split, idempotencia). Existujúca
-- `podpora` ostáva ako read-projekcia (AFTER INSERT trigger) → „Čo podporujem“
-- a charita mappery čítajú ďalej bez zmeny.
-- Interné ID prípadu = `prispevok.id`; verejné poradie = `prispevok.cislo`.
-- Externé rails SIMULOVANÉ (chain hash / VS / SMS kód) — non-custody.
--
-- POZN. RLS: TEST-ONLY (using true) — rovnaká konvencia ako 0001/0003;
--       produkčné owner-only RLS = Fáza 5. Zápis ide cez SECURITY DEFINER
--       RPC `platba_create` (jediná zapisovacia cesta).
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

-- variabilný symbol (FIAT) — sekvenčný → garantovane unikátny (8–10 cifier)
create sequence if not exists public.vs_seq start with 1000000001;

-- ---------- BATCH (24h agregátne zúčtovanie mikro-DEED) ----------
create table public.platba_batch (
  id          uuid primary key default gen_random_uuid(),
  okno_od     timestamptz not null,
  okno_do     timestamptz not null,
  stav        text not null default 'open' check (stav in ('open','closing','settled','failed')),
  pocet       int not null default 0,
  suma_spolu  numeric(18,4) not null default 0,
  settle_hash text,                                  -- jeden simulovaný agregátny tx hash
  idem_kluc   text not null unique,                  -- 'batch:'||epoch(minútová hranica) → 1 batch / okno
  vytvorene   timestamptz not null default now(),
  settled_at  timestamptz,
  unique (okno_od, okno_do)
);

-- ---------- PLATBA (system-of-record) ----------
create table public.platba (
  id              uuid primary key default gen_random_uuid(),
  verejne_cislo   bigint generated by default as identity,        -- verejné poradie platby
  case_id         uuid references public.prispevok(id) on delete set null,  -- interné ID prípadu (NULL = tip/odznak bez prípadu)
  odosielatel     uuid references public.ucet(id) on delete set null,       -- darca (NULL = anon/host)
  odosielatel_text text,                                          -- denormalizovaný darca (demo/seed)
  prijemca_ucet   uuid references public.ucet(id) on delete set null,
  prijemca_text   text,                                           -- denormalizovaný príjemca
  suma            numeric(14,4) not null check (suma > 0),         -- 4dp: mikro DEED je sub-cent
  mena            text not null check (mena in ('DEED','EUR')),
  kanal           text not null check (kanal in ('deed','fiat','sms','sepa')),
  -- externý identifikátor podľa kanála (práve jeden podľa kanála)
  ext_vs          text,                                           -- FIAT: variabilný symbol
  ext_hash        text,                                           -- DEED: (simulovaný) chain hash
  ext_sms_kod     text,                                           -- SMS: kód brány
  -- poplatky
  poplatok        numeric(14,4) not null default 0,               -- celkový poplatok (procesor + marža)
  marza           numeric(14,4) not null default 0,               -- naša marža (časť poplatku)
  cista_suma      numeric(14,4) not null default 0,               -- príjemcovi po poplatku
  tip             numeric(14,4) not null default 0,               -- dobrovoľný tip (SEPA) → platforme
  -- životný cyklus
  stav            text not null default 'pending'
                    check (stav in ('pending','credited','settled','failed','refunded')),
  -- credited = interný ledger sa pohol (counter hneď); settled = externe zúčtované
  batch_id        uuid references public.platba_batch(id) on delete set null,  -- len mikro-DEED
  idem_kluc       text not null unique,                           -- 1 klik = 1 kľúč → duplicitný tap = no-op
  parent_id       uuid references public.platba(id) on delete set null,        -- recurring/split rodič
  meta            jsonb not null default '{}'::jsonb,             -- snapshot vyzbierane/ciel/source/escrow_id…
  credited_at     timestamptz,
  settled_at      timestamptz,
  cas             timestamptz not null default now(),
  vytvorene       timestamptz not null default now()
);
comment on table public.platba is 'Payment Engine — system-of-record pre každý pohyb peňazí (ledger).';

create unique index platba_ext_vs_uniq on public.platba (ext_vs) where ext_vs is not null;
create index on public.platba (case_id);
create index on public.platba (odosielatel);
create index on public.platba (prijemca_ucet);
create index on public.platba (stav);
create index on public.platba (kanal, stav);
-- horúci index batchu: nezúčtované mikro-DEED, najstaršie prvé
create index platba_batch_hot on public.platba (vytvorene)
  where kanal = 'deed' and stav = 'credited' and batch_id is null;

-- ---------- SPLIT (jedna platba → N príjemcov podľa pomeru) ----------
create table public.platba_split (
  id            bigint generated always as identity primary key,
  platba_id     uuid not null references public.platba(id) on delete cascade,
  prijemca      uuid references public.ucet(id) on delete set null,
  prijemca_text text,
  podiel        numeric(6,5) not null check (podiel > 0 and podiel <= 1),  -- 0.30000
  suma          numeric(14,4) not null,
  fixny         boolean not null default false                  -- org-fixovaný vs darcom-voľný
);
create index on public.platba_split (platba_id);

-- ---------- ESCROW (30/70 Learn, matching, milestone) — logika vo Fáze 4 ----------
create table public.escrow (
  id          uuid primary key default gen_random_uuid(),
  case_id     uuid references public.prispevok(id) on delete set null,
  typ         text not null check (typ in ('rozdelene_30_70','matching','milestone')),
  vklad       numeric(14,4) not null,
  zostatok    numeric(14,4) not null,
  mena        text not null check (mena in ('DEED','EUR')),
  sponzor     uuid references public.ucet(id) on delete set null,
  pravidlo    jsonb not null default '{}'::jsonb,               -- {target, matchedRatio, splitFirst:0.3 …}
  stav        text not null default 'aktivny' check (stav in ('aktivny','uvolneny','vrateny','vycerpany')),
  vytvorene   timestamptz not null default now()
);
create index on public.escrow (case_id);

-- ---------- RECURRING (LEN charita) — scheduler vo Fáze 4 ----------
create table public.opakovana_platba (
  id                 uuid primary key default gen_random_uuid(),
  rozsah             text not null check (rozsah in ('request','segment','charita')),
  case_id            uuid references public.prispevok(id) on delete set null,    -- rozsah='request'
  segment_id         bigint,                                   -- rozsah='segment' (FK na segmenty neskôr)
  charita_ucet       uuid references public.ucet(id) on delete cascade,
  darca              uuid references public.ucet(id) on delete cascade,
  suma               numeric(14,4) not null,
  mena               text not null check (mena in ('DEED','EUR')),
  perioda            text not null check (perioda in ('tyzdenne','mesacne','rocne')),
  viazane_na_zbierku boolean not null default false,           -- request: stop pri ukončení zbierky
  stav               text not null default 'aktivny' check (stav in ('aktivny','zruseny','ukonceny')),
  dalsia_platba      timestamptz,
  vytvorene          timestamptz not null default now()
);
create index on public.opakovana_platba (darca);
create index on public.opakovana_platba (stav, dalsia_platba);

-- ============================================================
-- KOMPAT-TRIGGER: platba → podpora (read-projekcia)
-- „Čo podporujem“ + charita mappery čítajú `podpora` bez zmeny.
-- podpora.kanal nemá 'sepa' → mapujeme na 'fiat'; suma sa zaokrúhli na 2dp.
-- ============================================================
create or replace function public.platba_do_podpory() returns trigger
language plpgsql as $fn$
begin
  insert into public.podpora (ucet_id, prispevok_id, prijemca, suma, kanal, darca_nazov, vyzbierane, ciel, cas)
  values (
    NEW.odosielatel,
    NEW.case_id,
    NEW.prijemca_text,
    round(NEW.suma, 2),
    case when NEW.kanal = 'sepa' then 'fiat' else NEW.kanal end,
    NEW.odosielatel_text,
    nullif(NEW.meta->>'vyzbierane','')::numeric,
    nullif(NEW.meta->>'ciel','')::numeric,
    NEW.cas
  );
  return NEW;
end;
$fn$;

create trigger trg_platba_do_podpory
  after insert on public.platba
  for each row execute function public.platba_do_podpory();

-- ============================================================
-- RPC platba_create — jediná zapisovacia cesta (idempotentná, instant-credit)
-- ============================================================
create or replace function public.platba_create(
  p_idem_kluc        text,
  p_suma             numeric,
  p_mena             text,
  p_kanal            text,
  p_case_id          uuid    default null,
  p_odosielatel      uuid    default null,
  p_odosielatel_text text    default null,
  p_prijemca_ucet    uuid    default null,
  p_prijemca_text    text    default null,
  p_obe_registrovane boolean default false,
  p_tip              numeric default 0,
  p_meta             jsonb   default '{}'::jsonb
) returns public.platba
language plpgsql security definer set search_path = public, extensions as $fn$
declare
  v_existuje  public.platba;
  v_marza     numeric(14,4) := 0;
  v_poplatok  numeric(14,4) := 0;
  v_cista     numeric(14,4);
  v_mikro     boolean := (p_kanal = 'deed' and p_suma <= 1);
  v_stav      text := 'pending';
  v_vs        text := null;
  v_hash      text := null;
  v_sms       text := null;
  v_credited  timestamptz := null;
  v_settled   timestamptz := null;
  v_row       public.platba;
begin
  -- idempotencia: rovnaký kľúč → vráť existujúci riadok (duplicitný tap = no-op)
  select * into v_existuje from public.platba where idem_kluc = p_idem_kluc;
  if found then return v_existuje; end if;

  -- poplatky (placeholder krivka; reálna degresia = tokenomika)
  if p_kanal = 'deed' then
    if p_suma <= 0.5 and p_obe_registrovane then v_marza := 0;          -- mikro 0€
    else v_marza := round(p_suma * 0.03, 4); end if;                    -- DEED ~3 %
    v_poplatok := v_marza;
  elsif p_kanal = 'sepa' then
    v_marza := 0; v_poplatok := 0;                                      -- SEPA 0 % marža
  elsif p_kanal = 'fiat' then
    v_marza := round(p_suma * 0.015, 4);
    v_poplatok := round(p_suma * 0.014 + 0.15 + v_marza, 4);            -- procesor + marža
  elsif p_kanal = 'sms' then
    v_marza := round(p_suma * 0.05, 4);
    v_poplatok := round(p_suma * 0.10 + v_marza, 4);                    -- operátor + marža
  end if;
  v_cista := round(p_suma - v_poplatok, 4);

  -- stav + externý identifikátor podľa kanála
  if v_mikro then
    -- mikro-DEED: pripíš HNEĎ (counter), zúčtuj v 24h batchi
    v_stav := 'credited'; v_credited := now();
  elsif p_kanal = 'deed' then
    v_stav := 'settled'; v_credited := now(); v_settled := now();
    v_hash := '0x' || encode(gen_random_bytes(8), 'hex');               -- simulovaný chain hash
  elsif p_kanal in ('fiat','sepa') then
    v_stav := 'settled'; v_credited := now(); v_settled := now();
    v_vs := lpad(nextval('public.vs_seq')::text, 10, '0');             -- variabilný symbol
  elsif p_kanal = 'sms' then
    v_stav := 'settled'; v_credited := now(); v_settled := now();
    v_sms := upper(encode(gen_random_bytes(3), 'hex'));                 -- kód brány
  end if;

  insert into public.platba (
    case_id, odosielatel, odosielatel_text, prijemca_ucet, prijemca_text,
    suma, mena, kanal, ext_vs, ext_hash, ext_sms_kod,
    poplatok, marza, cista_suma, tip, stav, idem_kluc, meta, credited_at, settled_at
  ) values (
    p_case_id, p_odosielatel, p_odosielatel_text, p_prijemca_ucet, p_prijemca_text,
    p_suma, p_mena, p_kanal, v_vs, v_hash, v_sms,
    v_poplatok, v_marza, v_cista, coalesce(p_tip,0), v_stav, p_idem_kluc, coalesce(p_meta,'{}'::jsonb),
    v_credited, v_settled
  )
  on conflict (idem_kluc) do nothing
  returning * into v_row;

  -- súbeh na idem_kluc: iný request medzitým vložil → vráť ten
  if v_row.id is null then
    select * into v_row from public.platba where idem_kluc = p_idem_kluc;
    return v_row;
  end if;

  -- živý counter prípadu sa hýbe HNEĎ (aj pri mikro pred batchom)
  if p_case_id is not null then
    update public.prispevok
      set vyzbierane = coalesce(vyzbierane, 0) + p_suma,
          podpora_count = coalesce(podpora_count, 0) + 1
      where id = p_case_id;
  end if;

  return v_row;
end;
$fn$;

grant execute on function public.platba_create(text,numeric,text,text,uuid,uuid,text,uuid,text,boolean,numeric,jsonb) to anon, authenticated;

-- ============================================================
-- RPC platba_batch_close — idempotentné 24h dávkové zúčtovanie mikro-DEED
-- Idempotencia: unique okno + idem_kluc + claiming UPDATE … where batch_id is null.
-- ============================================================
create or replace function public.platba_batch_close(p_do timestamptz default now())
returns public.platba_batch
language plpgsql security definer set search_path = public, extensions as $fn$
declare
  v_hranica timestamptz := date_trunc('minute', p_do);   -- minútová hranica (idempotencia v rámci minúty)
  v_od      timestamptz := v_hranica - interval '24 hours';
  v_idem    text := 'batch:' || extract(epoch from v_hranica)::bigint::text;
  v_batch   public.platba_batch;
begin
  -- jedna dávka na okno; opakované volania (cron + manuál) = no-op
  insert into public.platba_batch (okno_od, okno_do, stav, idem_kluc)
    values (v_od, v_hranica, 'closing', v_idem)
    on conflict (idem_kluc) do nothing
    returning * into v_batch;

  if v_batch.id is null then
    select * into v_batch from public.platba_batch where idem_kluc = v_idem;
    if v_batch.stav = 'settled' then return v_batch; end if;  -- už hotové
  end if;

  -- claim: priradí VŠETKY nezúčtované mikro-DEED do tejto dávky (atomicky, nikdy 2×).
  -- Bez časového filtra: credited riadok je durabilný hneď, settle ho len „označí“;
  -- 24h je kadencia spúšťača (pg_cron), nie tvrdý filter (inak by sa stratili
  -- riadky z aktuálneho okna). Idempotenciu drží idem_kluc (1 dávka / minútu).
  update public.platba
    set batch_id = v_batch.id, stav = 'settled', settled_at = now()
    where kanal = 'deed' and stav = 'credited' and batch_id is null;

  -- agregát + jeden settle hash
  update public.platba_batch b set
    pocet       = (select count(*) from public.platba where batch_id = v_batch.id),
    suma_spolu  = (select coalesce(sum(suma),0) from public.platba where batch_id = v_batch.id),
    settle_hash = coalesce(b.settle_hash, '0x' || encode(gen_random_bytes(8), 'hex')),
    stav        = 'settled',
    settled_at  = now()
    where b.id = v_batch.id
    returning * into v_batch;

  return v_batch;
end;
$fn$;

grant execute on function public.platba_batch_close(timestamptz) to anon, authenticated;

-- ---------- RLS (TEST-ONLY: povoliť všetko pre anon/authenticated) ----------
do $$
declare t text;
begin
  foreach t in array array['platba','platba_batch','platba_split','escrow','opakovana_platba'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists test_all_access on public.%I', t);
    execute format(
      'create policy test_all_access on public.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;
