-- ============================================================
-- 0024 · Záujmy osoby — 10 oblastí (karta 18). Registrácia aj profil čítajú ten istý zoznam.
-- Zdroj: src/lib/personalizaciaStore.ts ZAUJMY_KATALOG (oblasť = label).
-- Staré oblasti a pod-položky sa len vypnú (aktivny = false), nič sa nemaže.
-- ============================================================
update public.cis_zaujmy set aktivny = false;

insert into public.cis_zaujmy (oblast, pod_polozka, poradie) values
  ('Komunita','Dobrovoľníctvo',1),
  ('Komunita','Susedská výpomoc',2),
  ('Komunita','Komunitné podujatia',3),
  ('Komunita','Seniori',4),
  ('Komunita','Deti a mládež',5),
  ('Komunita','Zbierky a dary',6),
  ('Hudba','Rock/tvrdšie',1),
  ('Hudba','Pop',2),
  ('Hudba','Rap/hip-hop',3),
  ('Hudba','Elektronická',4),
  ('Hudba','Tradičné',5),
  ('Hudba','Jazz/blues',6),
  ('Hudba','Klasická',7),
  ('Hudba','Svetová',8),
  ('Šport','Tímové/loptové',1),
  ('Šport','Raketové',2),
  ('Šport','Beh a vytrvalosť',3),
  ('Šport','Cyklistika',4),
  ('Šport','Vodné športy',5),
  ('Šport','Zimné športy',6),
  ('Šport','Sila/fitness',7),
  ('Šport','Bojové športy',8),
  ('Šport','Outdoor/hory',9),
  ('Šport','Precízne/mentálne',10),
  ('Šport','Pohyb/tanec',11),
  ('Šport','Iné',12),
  ('Zdravie','Výživa/strava',1),
  ('Zdravie','Pohyb/telo',2),
  ('Zdravie','Duševné zdravie',3),
  ('Zdravie','Prevencia',4),
  ('Zdravie','Závislosti',5),
  ('Zdravie','Skupiny',6),
  ('Príroda','Akcie',1),
  ('Príroda','Životný štýl',2),
  ('Príroda','Ochrana prírody',3),
  ('Príroda','Udržateľnosť',4),
  ('Príroda','Eko pestovanie/záhrada',5),
  ('Zvieratá','Útulky',1),
  ('Zvieratá','Adopcia',2),
  ('Zvieratá','Venčenie a dočasná opatera',3),
  ('Zvieratá','Veterinárna pomoc',4),
  ('Zvieratá','Voľne žijúce zvieratá',5),
  ('Zvieratá','Kastračné programy',6),
  ('Umenie','Výtvarné',1),
  ('Umenie','Priestorové',2),
  ('Umenie','Fotografia',3),
  ('Umenie','Film/video',4),
  ('Umenie','Scénické',5),
  ('Umenie','Literatúra',6),
  ('Umenie','Dizajn/remeslá',7),
  ('Umenie','Digitálne',8),
  ('Učenie','Jazyky',1),
  ('Učenie','IT/tech',2),
  ('Učenie','Financie/právo',3),
  ('Učenie','Remeslá/praktické',4),
  ('Učenie','Soft skills',5),
  ('Učenie','Veda',6),
  ('Učenie','Doučovanie',7),
  ('Učenie','Technické hobby',8),
  ('Pomoc','Finančná pomoc',1),
  ('Pomoc','Materiálna pomoc',2),
  ('Pomoc','Doučovanie/mentoring',3),
  ('Pomoc','Sprevádzanie/asistencia',4),
  ('Pomoc','Krízová pomoc',5),
  ('Pomoc','Psychická podpora',6),
  ('Viera','Omše a bohoslužby',1),
  ('Viera','Farské akcie',2),
  ('Viera','Modlitbové stretnutia',3),
  ('Viera','Púte',4),
  ('Viera','Mládež vo farnosti',5),
  ('Viera','Farská charita',6),
  ('Viera','Duchovná hudba',7)
on conflict (oblast, pod_polozka) do update set poradie = excluded.poradie, aktivny = true;
